# Generated by Django 5.2.4 on 2025-08-26 06:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentANPByProductYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('LIFE_RP', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('LIFE_SP', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('HEALTH_SHIELD', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('PA', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('CS', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('TOTAL_ANP', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of LIFE_RP + LIFE_SP + HEALTH_SHIELD + PA + CS', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'agent_code__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_anp_by_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_anp_by_product_yearly',
                'indexes': [models.Index(fields=['year', 'agent'], name='agent_anp_b_year_600297_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'year'), name='uniq_agent_year')],
            },
        ),
        migrations.CreateModel(
            name='AgentCasePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('TOP_QUARTILE_MTD', models.CharField(choices=[('TERMINATED', 'TERMINATED'), ('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('TOP_QUARTILE_YTD', models.CharField(choices=[('TERMINATED', 'TERMINATED'), ('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('JAN', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('FEB', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('MAR', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('APR', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('MAY', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('JUN', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('JUL', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('AUG', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('SEP', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('OCT', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('NOV', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('DEC', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('YTD_CASE', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('YTD_GROWTH', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('-1.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))])),
                ('YTD_CONTRIBUTION_TO_UNIT', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))])),
                ('agent', models.ForeignKey(limit_choices_to={'agent_code__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='case_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_case_performance',
                'indexes': [models.Index(fields=['year', 'agent'], name='agent_case__year_b6af89_idx'), models.Index(fields=['TOP_QUARTILE_MTD'], name='agent_case__TOP_QUA_3f9121_idx'), models.Index(fields=['TOP_QUARTILE_YTD'], name='agent_case__TOP_QUA_f6046b_idx')],
                'unique_together': {('agent', 'year')},
            },
        ),
    ]
