# Generated by Django 5.2.4 on 2025-08-29 17:01

import django.core.validators
import insurance_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANPImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ANP Data Import', max_length=255)),
                ('excel_file', models.FileField(help_text='Upload Excel file with ANP data', upload_to=insurance_data.models.upload_excel_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(choices=[(1, '01 - Jan'), (2, '02 - Feb'), (3, '03 - Mar'), (4, '04 - Apr'), (5, '05 - May'), (6, '06 - Jun'), (7, '07 - Jul'), (8, '08 - Aug'), (9, '09 - Sep'), (10, '10 - Oct'), (11, '11 - Nov'), (12, '12 - Dec')], verbose_name='Month')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('import_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ANP Excel Import',
                'verbose_name_plural': 'ANP Excel Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ANP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Agent Name')),
                ('life_rp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Life RP')),
                ('life_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Life SP')),
                ('health_shield', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Health Shield')),
                ('pa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PA')),
                ('cs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CS')),
                ('total_anp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total ANP')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ANP Record',
                'verbose_name_plural': 'ANP Records',
                'ordering': ['-year', '-month', 'agent_name'],
                'unique_together': {('agent_name', 'year', 'month')},
            },
        ),
    ]
