# Generated by Django 5.2.4 on 2025-08-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0002_anpimport_anp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anpimport',
            name='title',
        ),
    ]
