# Generated by Django 5.2.4 on 2025-08-30 05:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0003_remove_anpimport_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCountImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('excel_file', models.FileField(help_text='Upload Excel file with ANP data', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='agentcaseperformance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='agentcaseperformance',
            name='agent',
        ),
        migrations.CreateModel(
            name='CaseCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('TOP_QUARTILE_MTD', models.CharField(choices=[('TERMINATED', 'TERMINATED'), ('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('TOP_QUARTILE_YTD', models.CharField(choices=[('TERMINATED', 'TERMINATED'), ('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('JAN', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('FEB', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('MAR', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('APR', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('MAY', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('JUN', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('JUL', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('AUG', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('SEP', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('OCT', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('NOV', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('DEC', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('YTD_CASE', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('YTD_GROWTH', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('-1.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))])),
                ('YTD_CONTRIBUTION_TO_UNIT', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))])),
                ('agent', models.ForeignKey(limit_choices_to={'agent_code__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='case_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Count',
                'verbose_name_plural': 'Case Counts',
            },
        ),
        migrations.DeleteModel(
            name='AgentANPByProductYearly',
        ),
        migrations.DeleteModel(
            name='AgentCasePerformance',
        ),
    ]
