# Generated by Django 5.2.4 on 2025-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0004_casecountimport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecount',
            name='TOP_QUARTILE_MTD',
            field=models.CharField(choices=[('TERMINATED', 'TERMINATED'), ('IN', 'IN'), ('OUT', 'OUT'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='casecount',
            name='TOP_QUARTILE_YTD',
            field=models.CharField(choices=[('TERMINATED', 'TERMINATED'), ('IN', 'IN'), ('OUT', 'OUT'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
