# Generated by Django 5.2.4 on 2025-09-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0006_fycimport_fyc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fyc',
            options={'verbose_name': 'FYC', 'verbose_name_plural': 'FYC...'},
        ),
        migrations.RemoveField(
            model_name='fyc',
            name='YTD_CASE',
        ),
    ]
