# Generated by Django 5.2.4 on 2025-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jtuser',
            name='education',
        ),
        migrations.AddField(
            model_name='jtuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
