# Generated by Django 5.2.4 on 2025-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jtuser',
            name='agent_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
