# Generated by Django 5.2.4 on 2025-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jtuser_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtuser',
            name='agent_code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
